name: rtmphm_services
networks:
  rtmpservices:
services:
  influxdb2:
    image: influxdb:2
    user: 1000:1000
    restart: unless-stopped
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: rtmphealthmonitor
      DOCKER_INFLUXDB_INIT_PASSWORD: rtmphealthmonitor
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: changemetosomethingsecret
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: 1000:1000
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage: