services:
  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - rtmpservices
  logstash:
    ports:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    restart: unless-stopped
    networks:
      - rtmpservices

