backend:                                   # Backend configuration
  database:                                # Database configuration
    - type: prometheus                     # What database is being used (prometheus)
      host: ${db_host:-localhost}          # Hostname, or IP address, of the database
      port: ${db_port:-9090}               # Port of the database
      # username: {db_un:-rtmphm}          # Database username (not used in Prometheus)
      # password: {db_pw:-rtmphm}          # Database password (not used in Prometheus)
  reporting:                               # Reporting configuration
    - type: json_output                    # What reporting method is being used (json_output)
      port: 12000                          # Port to provide output on for HTTP GET requests
rtmpstreams:                               # Primary Heading, RTMP stream configurations
  - name: stream1                          # Stream name
    provider:                              # Provider (Stream) configuration            
      vimeo:                               # Provider name, Provider specific configuration follows
        eventid: '1231231'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
  - name: stream2
    provider:
      vimeo:
        eventid: '1231232'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
  - name: stream3
    provider:
      vimeo:
        eventid: '1231231'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
  - name: stream4
    provider:
      vimeo:
        eventid: '1231232'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
