backend:                                   # Backend configuration
  database:                                # Database configuration
    - type: influxdb                       # What database is being used
      host: ${db_host:-localhost}          # Hostname, or IP address, of the database
      port: ${db_port:-9090}               # Port of the database
      # username: {db_un:-rtmphm}          # Database username
      # password: {db_pw:-rtmphm}          # Database password
  reporting:                               # Reporting configuration
    - type: json_output                    # What reporting method is being used (json_output), mux of all data
      port: 12000                          # Port to provide output on for HTTP GET requests
  logging:                                 # Logging setup
    level: debug                           # Log at what level possible, {debug, error, warning, info}
    location: /var/log/rtmphm.log          # Log path
    retention: 10                          # Log retention in days
speedtest:                                 # Speedtest definitions, if ommited no speedtest will be performed
  polling_time: 10                         # How often speedtest performed, in seconds
  server:                                  # what server to use, if undefined default to speedtest.net
streams:                                   # Primary Heading, stream configurations
  - name: stream1                          # Stream name
    provider:                              # Provider (Stream) configuration            
      vimeolive:                           # Provider name, Provider specific configuration follows
        eventid: '1231231'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
      polling_time: 2                     # How often is stream probed, in seconds
    hardware:
      webpresentor:
        ip_address: 192.192.192.192
  - name: stream2
    provider:
      vimeolive:
        eventid: '1231232'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
      polling_time: 2
    hardware:
      webpresentor:
        ip_address: 192.192.192.192
  - name: stream3
    provider:
      vimeolive:
        eventid: '1231233'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
      polling_time: 2
    hardware:
      webpresentor:
        ip_address: 192.192.192.192
  - name: stream4
    provider:
      vimeolive:
        eventid: '123124'
        vimeo_token: ${vimeo_token}
        vimeo_key: ${vimeo_key}
        vimeo_secret: ${vimeo_secret}
      polling_time: 2
    hardware:
      webpresentor:
        ip_address: 192.192.192.192