global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
  scrape_failure_log_file: /prometheus/logs/scrape_failure.log
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090
  - job_name: WebPresentor1A
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /control/api/v1/livestreams/0
    scheme: http
    static_configs:
    - targets:
      - 172.63.6.26
  - job_name: WebPresentor2A
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /control/api/v1/livestreams/0
    scheme: http
    static_configs:
    - targets:
      - 172.63.6.27
  - job_name: WebPresentor3A
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /control/api/v1/livestreams/0
    scheme: http
    static_configs:
    - targets:
      - 172.63.6.28
  - job_name: WebPresentor4A
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /control/api/v1/livestreams/0
    scheme: http
    static_configs:
    - targets:
      - 172.63.6.29